### ISSUE TITLE
The metric system is not accurate

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1228]
Originally in GitLab by @gvictorpcruz

I would like to request a small improvement that adds a small button to the sheet, where you can convert with one click all items and spells to the metric system.

It was really nice to add this in 1.4, but the compendiums are still imperial, and having to manually adapt all the items in a sheet to the metric system, it sucks.

There is a module called Metric System for D&D5e that did this in 7.9 and it was wonderful, unfortunately DEV abandoned it and it would be great for us Brazilians/French/Germans to have a tool that transforms range values ​​and areas of effect in an automated way.

**Comment by alexdiste** [comment]
In Italian is still wrong.

Also in italian rule tell STR*7.5 and 2 lbs for 1 Kg. Meanwhile seems now Foundry use STR*6.8

**Comment by FalconPilot** [comment]
Hey! I know it's an old post, but I have some insight on how the metric system is handled for DND5e, since I'm french and played at the same time games using the imperial AND metric systems 😄 

The conversion actually is simple:
- 5ft gets converted to 1.5 meters (I know, it's gonna require float numbers... this could be a problem)
- 1lb gets converted to 500g (so it just has to be divided by 2)
- 1 mile gets converted to 1.5km as far as I know

Those are all the conversion rates I've seen in at the very least the french, italian and german editions. It seems to be pretty much standardized across the board by WotC.

So when it comes to strength @aaclayton the weight rate conversion is also applied: instead of "1 Strength = 15lb of encumbrance", it becomes "1 Strength = 7.5kg of encumbrance"

If you have extra questions about the metric system usage, I'm available to answer them, as I played extensively with it in official european editions! (And have a french core rulebook at hand)
