### ISSUE TITLE
Using max() in an attack roll bonus field on an item results in StringTerm error

### ISSUE THREAD

**Issue by IHaveThatPower** [foundryvtt/dnd5e#1779]
Foundry 10.284, dnd5e 2.0.2, all modules disabled. Conferring on Discord in the dnd5e channel, this does _not_ happen on Foundry v9.

Repro steps:
1. Create a weapon item and give it to an actor
2. Set the Weapon Attack Action Type to Ranged Weapon Attack
3. Set Ability Modifier to Dexterity
4. Set the Attack Roll Bonus to `1 + max(@ablities.int.mod, @abilities.dex.mod) - @abilities.dex.mod`
5. Set the Damage Formula to `2d10 + max(@abilities.dex.mod, @abilities.int.mod) + 1`
6. Click the 'Roll' icon for the weapon
7. Click the 'Attack' option for the weapon

Expected:
Roll evaluates

Actual:
No evaluation occurs, and the following error appears in the console:
```
foundry.js:11551 Uncaught (in promise) Error: Unresolved StringTerm 5,6 requested for evaluation
[Detected 1 package: system:dnd5e]
    at StringTerm.evaluate (foundry.js:11551:11)
    at Roll._evaluate (foundry.js:9113:42)
    at async MathTerm._evaluate (foundry.js:10966:7)
    at async D20Roll._evaluate (foundry.js:9100:9)
    at async d20Roll (dice.mjs:96:3)
    at async Item5e.rollAttack (item.mjs:1323:18)
    at async Item5e._onChatCardAction (item.mjs:1803:9)
```
(`5,6` was the evaluation of the two terms in the `max()` function above in my test use case)

The damage term evaluates without issue.

**Comment by arbron** [comment]
@Fyorl Can you check this out and see if this might be a core issue?

**Comment by Fyorl** [comment]
It's being caused by a quite obscure interaction between the `D20Roll` class and the underlying `Roll` code. So technically a `dnd5e` bug. If you select the token and run this in the console:

```
Roll.parse("1d20 + 1 + max(@abilities.int.mod, @abilities.dex.mod) - @abilities.dex.mod + @mod", _token.actor.getRollData());
```

It correctly results in a `MathTerm` with inner `terms` of `['6', '5']`. But if you check the `roll.terms` just before it is evaluated in `d20roll`, the `MathTerm` has inner `terms` of `['6,5']`. This seems to be because, when we get to the part of `Roll` parsing where we invoke `Roll._splitMathArgs`, there's a bit of logic which tries to `validate` the individual arguments by calling `new this(formula)` and `D20Roll` throws an error here because `6` is not a valid 'd20 roll'.

This behaviour did change in v10 as part of #6905 (whose issue body seems to have gotten a bit borked in the migration from GitLab).
