### ISSUE TITLE
[BUG] The method toObject() on a actor broke the AC data

### ISSUE THREAD

**Issue by p4535992** [foundryvtt/dnd5e#1830]
System version: Dnd5e 2.0.3
Foundryvtt Version: 10.286

So i'm working on a module, and when i retrieve a actor by id 

```
const myActor = game.actors.get(id);
```
all the AC value are correct.

```
ac: {
  armor: 10
  base: 11
  bonus: 0
  calc: "natural"
  cover: 0
  flat: 11
  formula: ""
  min: 11
  shield: 0
  value: 11
}
```

When i invoke :

```
const  myActorBroken = myActor.toObject();
```

i get this:

```
ac: {
  calc: "natural"
  flat: undefined
  formula: ""
  min: 11
}
```
 Here a image:

![img](https://i.imgur.com/ff1qBde.png)

is a bug or is the correct behaviour ?

**Comment by arbron** [comment]
Do you have an active effect targeting `attributes.ac.flat`? If so, then otherwise everything else looks correct. Remember, calling `toObject()` only returns the source data, not any derived values. The only bits of AC data we actually need to save to the database are the calculation mode, formula, and flat value. Everything is calculated from those and your equipment.

**Comment by p4535992** [comment]
No active effect it just the giant octopus from the dnd5 srd compendium.
Maybe there is some derived data from the system dnd5e himself ?
I'll close the issue the solution fro anyone interested was to use mergeObject and deepClone helper of foundryvtt.

**Comment by tposney** [comment]
If you want to get the full system data - can't you to ``actor.toOjbect(false)``?

**Comment by p4535992** [comment]
ty @tposney  a much easier solution, didn't know about that parameter
