### ISSUE TITLE
Pact Slots Not Fully Refreshed on Rest

### ISSUE THREAD

**Issue by Razmeth** [foundryvtt/dnd5e#1831]
I have given a character an item which increases the max number of pact slots.  This modifies 'system.spells.pact.max' to 'Add' '1', and it properly increases the max pact slots; at lvl 9 Warlock this increases it from 2 slots to 3 and works correctly.  However, when you rest (short or long), it only restores up to the normal maximum of 2, not the new maximum of 3.

**Comment by tposney** [comment]
pact.level is force set to Math.min(pact.level, pact.max) in _prepareSpellCasting overwriting the value in actor._source, before I get a chance to change pact.max.

This is not done for other spell slots. Is it really necessary to do so for pact spell slots?

Alternatively could we introduce bonus fields for spell/pact slots so that the issue does not arise?

**Comment by krbz999** [comment]
> pact.level is force set to Math.min(pact.level, pact.max) in _prepareSpellCasting overwriting the value in actor._source, before I get a chance to change pact.max.
> This is not done for other spell slots. Is it really necessary to do so for pact spell slots?
> Alternatively could we introduce bonus fields for spell/pact slots so that the issue does not arise?

You can use `pact.override`. I tested this, and a short/long rest will then properly restore all Pact Slots (without DAE).
