### ISSUE TITLE
The Maximum Uses Formula within Action Surge has references to missing data: @scale.fighter.action-surge

### ISSUE THREAD

**Issue by scottjfox1984** [foundryvtt/dnd5e#1842]
i was working with a character sheet for the dnd5e and i noticed the action surge formula isnt working, not sure if this is a bug or just incorrect formula, but can someone help please?

Error: You are accessing Item5e#data which has been migrated to Item5e#system
Deprecated since Version 10 Backwards-compatible support will be removed in Version 12

im not sure where to find the correct attributes to replace this.

**Comment by scottjfox1984** [comment]
*	Did you add the Fighter class from the SRD compendium, import it from somewhere else, or did you create it yourself? Yes I created it from the Compendium
*	If you imported or created it, does it have the proper "Action Surge" scale value in its Advancement tab? Where is the advancement  tab? 

*	If I go to details I see this under limited uses 0 of @scale.fighter.action-surge per Short Rest, im assuming @scale.fighter.action-surge is the failure here

*	Does this occur with no modules enabled? Yes it does
*	What is the entire error log for deprecated issue?

*	Where would I see the error log for this?
*	 

This is the screen I see

**Comment by LanMan04** [comment]
I also have this same issue on v10, FYI.

**Comment by naven87** [comment]
I'm also seeing the same thing.  Did anyone figure out what the cause was?

**Comment by MaxPat931** [comment]
The screenshot above shows an item imported from the DDBeyond importer, the reference shown in the description shows the reference instead of the number, because those references aren't evaluated in descriptions as tracked in this issue: https://github.com/foundryvtt/dnd5e/issues/1238

Otherwise, if you're having an issue with the Action Surge item, check the `Class Features (SRD)` compendium and how the Fighter Class is built in the `Classes (SRD)` compendium
![image](https://user-images.githubusercontent.com/86370342/209635851-8f4b7be5-8da8-494a-b47f-1a42dae1a396.png)
