### ISSUE TITLE
[Bug] Active effect showing as token status effect even when the effect is unavailable

### ISSUE THREAD

**Issue by LightingBoltSpark** [foundryvtt/dnd5e#1859]
_Used DAE (Dynamic Effects using Active Effects) module to show the "Force display on token" field, but I was told that field modifies **flags.core.statusId**_

1. Create an AE on an Equipment item ("Shield" in this example).
2. On that AE, check "Transfer to actor on item equip" and paste the Effect Icon path in "Force display on token" (DAE).
3. Drag and drop the Equipment to a character sheet.
4. Even when unequipped, the token status effect is showing on the token (while the AE is unavailable under "Effects").

The expected result would be: only show the status effect when the item is equipped (and the effect is active).

I don't know if this is intended or is a bug: if it's intended, it can be labeled as a "Feature request".

**Comment by the-real-orson** [comment]
The issue is that when the Item becomes unequipped, the effect is suppressed; however, it never becomes disabled.  So its state on the actor is: { isSuppressed: true, disabled: false }

**Comment by Krigsmaskine** [comment]
Assuming the issue is related, this also happens with items that need attunement, if the ActiveEffect has a duration. No modules involved.

1. Create an item with an ActiveEffect with a duration
2. Drag item onto a character sheet.

(Screenshot is of an unlinked token, but it's the same with a linked one.)
![image](https://user-images.githubusercontent.com/39592771/231002275-8287a21c-ccb9-4971-940c-50f8a13acbdf.png)

**Comment by Fyorl** [comment]
On v11 at least, this no longer appears to be an issue since `ActiveEffect#active` takes into account the `isSuppressed` state of the Active Effect.
