### ISSUE TITLE
Add custom enrichers for rolling checks & saves

### ISSUE THREAD

**Issue by arbron** [foundryvtt/dnd5e#1865]
Currently people are attempting to implement skill check buttons in descriptions using the format `1d20 + @skills.stl.total`, but this doesn't take into account all of the potential bonuses that apply nor does it display the roll dialog to allow selection of Advantage. Adding custom enrichers to the various system rolls would allow us to handle these inline rolls properly.

- ~`@Check{dex}`~ `@Check[dex]`: Roll a flat Dexterity check, displays as `Dexterity Check`
- ~`@Check{dex.acr}`~ `@Check[dex.acr]`: Roll an Acrobatics check using dexterity, displays as `Dexterity (Acrobatics) Check`
- ~`@Check{dex.acr|Leap}`~ `@Check[dex.acr]{Leap}`: Roll an Acrobatics check using dexterity, displays as `Leap`
- `@Check[dex.acr|15]`: Roll an Acrobatics DC 15 check using dexterity, displays as `DC 15 Dexterity (Acrobatics) Check`
- `@Check[dex.acr|dc:15]`: Explicitly adding the DC prefix would also be supported
- ~`@Save{dex}`~ `@Save[dex]`: Roll a Dexterity save, displays as `Dexterity Save`

Potentially also include a ~`@Skill{acr}`~ `@Skill[acr]` version that just uses the ability associated with a particular skill on the selected actor sheet.

### Alternative Spellings

- `@RollCheck`, `@RollSave`
- `@AbilityCheck`, `@AbilitySave`, `@SkillCheck`

**Comment by MaxPat931** [comment]
a `@RollItem{Bite}` which essentially calls `game.dnd5e.documents.macro.rollItem("Bite")` would also be useful for the Multiattack example I mentioned in #1546 which I've tinkered around and implemented with @kaelad02 's Inline Roll Commands module

**Comment by arbron** [comment]
It would also be useful to be able to reference certain rules without pointing to a specific journal:

- `@Reference{skill:acr}`: Opens the journal entry for actobatics
- `@Reference{condition:prone}` Opens the journal entry for prone

**Comment by kaelad02** [comment]
Like MaxPat mentioned, I made a module that does this that includes skills, ability checks, saves, and even items.

https://github.com/kaelad02/inline-roll-cmd

It uses a different syntax than you've suggested, imitating the deferred inline roll syntax, which allows you to specify the roll mode and add a label. I did that to give people options to make them specific rolls and labels, but if I'm being honest, I don't know how often that gets used. This simpler syntax you've suggest might be enough.

If you were okay with that syntax, I'd be willing to make a PR to donate that code to the system. I primarily made it because the system lacks a Skill action type but later found it useful in some cases where you could use an inline roll for an escape check or something. Now that I write that down, I wonder if we could also add one for an Escape check (i.e. the better of Athletics/Acrobatics). It's used for the defender of a grapple/shove attack as well as escaping monster's grapple attacks. I have a macro for that but we could add something like `@Escape` or `@Escape{15}` if we wanted to show a DC.

**Comment by mattexdee** [comment]
I wanted to propose an alternative syntax that would allow for setting a DC and sets the label more like content links. For example:

- `@Check[dex|dc:20]` would become `DC 20 Dexterity Check`
- `@Check[dex]`/`@Check[dex.acr]` would become `Dexterity Check`/`Dexterity (Acrobatics) Check`
- `@Check[dex.acr|dc:20]` would become `DC 20 Dexterity (Acrobatics) Check`
- `@Check[dex|dc:20]{DC 20 Jump}`/`@Check[dex.acr|dc:20]{DC 20 Jump}` would both become `DC 20 Jump`. 

Clicking the inline check could then roll the check and determine if it was successful or it could just send the challenge to the chat. If there's no DC it would send a chat message that players could click to roll the check.

I think the `@Save`, `@Reference`, and `@Skill` inline links could also be great inclusions. I would lean away from the `@RollCheck` alternative spellings as mistaken capitalization would be pretty easy to do.

**Comment by aaclayton** [comment]
Some perspective if it's helpful. In a separate (D&D) project we are currently using the following text enrichers for presenting inline checks/saves in text content:
```
[[save {abilityId} {dc}]]
[[ability {abilityId} {dc} {parentheses, optional}]]
[[skill {skillId} {dc} {abilityId, optional}]]
[[passive {skillId} {dc}]]
```
If a replacement syntax becomes officially supported by the base system we would do a process to convert all our usages of these to the 5e system approach, but I wanted to share what we are currently doing since I think it's worth considering.
I don't personally like @ as the magic symbol for this. For me @ is used to link to some other piece of content. This isn't a link to content, this is an inline action which is conceptually much closer to an inline roll like `[[/roll 4d6]]` or `[[4d6]]` than a content link. We chose double brackets for the consistency with inline rolls for that reason.
