### ISSUE TITLE
Shield is affecting Natural Armor twice 

### ISSUE THREAD

**Issue by MadManNBlueBox** [foundryvtt/dnd5e#1891]
When using a shield item with natural armor the bonus effects it twice over.

For my example I am using the SRD shield which has a +2 to AC.

This only happens when I have the shield equipped first.
 
When I input x into the config window for natural armor it forces it to x+2. Then if I hit update it has x+2+2.

Input 12
![unknown](https://user-images.githubusercontent.com/84350572/197856103-1c709178-30f9-434a-bdce-4cd83d2f527c.png)
Forces it to 14
![unknown](https://user-images.githubusercontent.com/84350572/197856257-1c5e7589-9c7f-4f29-a81f-b435773bbb33.png)
AC shows it is 16
![unknown](https://user-images.githubusercontent.com/84350572/197856341-b12e339f-29e4-4adf-9272-7742eba3fdb7.png)

**Comment by LiamFallon213** [comment]
Looked at this, it instead applies every time you update.

**Comment by LiamFallon213** [comment]
Looking deeper in, it seems like something is squashing everything down into a single value, including the shield bonus.

**Comment by LiamFallon213** [comment]
No clue where to go on this TBH

**Comment by kjolern** [comment]
Hi.  I tested this as well on Foundry v10 build 288. DND5e version 2.0.3.  It seems I can't reproduce the error.
Are you using the standard shield or the shield +2? Because the shield +2 is in addition to the normal +2 to AC. 
![shield](https://user-images.githubusercontent.com/79190020/200856284-00e835bc-a528-4022-a210-165efc4a54fb.png)

**Comment by kjolern** [comment]
Never mind my previous comment, I missed the update part. I see what you mean now.

**Comment by krbz999** [comment]
Seems that since the full AC value (bonuses and all) is applied in the Armor Class config, the only valid input field for 'natural' armor is forced to double-dip into any bonuses; this also applies to any ActiveEffects that are granting an AC bonus (`system.attributes.ac.bonus`), not just shields.

After some mucking about, I was able to prevent it by not calling `render` (in `armor-config.mjs`, L76):
```js
if ( event.currentTarget.name !== "ac.flat" ) this.render();
```
but I doubt that's an elegant solution, and it does not prevent AC from double-dipping on bonuses when switching to "Natural" through the `select`.
