### ISSUE TITLE
CONFIG doesn't change the default ability on skills on new actors

### ISSUE THREAD

**Issue by Omonox** [foundryvtt/dnd5e#1933]
When I was trying to change the default ability on skills it wouldn't work through a world script like this

`Hooks.once("setup", () => {
  CONFIG.DND5E.abilities.cha = "Discovery";
  const skillChanges = {
    dec: {ability: "int"},
    itm: {ability: "str"},
    per: {ability: "wis"},
    prf: {ability: "int"}
  };
  foundry.utils.mergeObject(CONFIG.DND5E.skills, skillChanges);
});`

I had to do a separate macro in order to get this to work. Strange thing is when you call CONFIG.DND5E.skills it came up with all the correct values. It just didn't change in the actor page. I tried creating new actors and restarting but to no avail.

**Comment by arbron** [comment]
This is because the default values are defined in `template.json`, and so are already set before `prepareBaseSkills` can get this data from the config. The best course of action here is probably just to not define any skills in `template.json` and let the upcoming `DataModel` implementation handle it all.

**Comment by Fyorl** [comment]
Marking this as blocked on #2388
