### ISSUE TITLE
Endless re-migration???

### ISSUE THREAD

**Issue by rtschaefer** [foundryvtt/dnd5e#2051]
I am not sure how else to report this (will try finding a Discord resource), but the update to 2.1.2 is sending an endless cascade of migration messages and when I log back in later, it performs the exact same compendium migrations.  The message "Applying DnD5E System Migration for version 2.1.2. Please be patient and do not close your game or shut down your server" never seems to go away...its been hours.

**Comment by unsoluble** [comment]
Return to Setup > Edit World > Launch in Safe Configuration. This will let the migration happen without modules enabled (and perhaps without crashing your server, which may be happening).

If this doesn’t help, or to otherwise follow up, please join us in the #dnd5e channel on the Discord — it’s a much better venue for general troubleshooting.
