### ISSUE TITLE
Features that are added manually to an actor while the level up automation window is open are removed when the level up automation is finished.

### ISSUE THREAD

**Issue by 0nionboi** [foundryvtt/dnd5e#2065]
This is in my hosted Foundry instance, latest edition of Foundry Version 10, Build 291, and DnD5e 2.1.2.  I turned off all modules to confirm.  
When you are going through the level up automation, any features that you add to that actor via dragging from the Items directory are removed when you click the "Complete" button at the end of the level up automation dialogue.

**Comment by 0nionboi** [comment]
I checked with a consumable Item and a Feature, both were removed from the sheet if they were added manually during the level up dialogue.

**Comment by MaxPat931** [comment]
This is currently expected behavior, but your use case may be addressed by the Item Choice Advancement in https://github.com/foundryvtt/dnd5e/pull/2015 (see the second video re: dropping an item into the Advancement itself)
For now you should wait until the Advancement process is complete to add items to the Actor.
