### ISSUE TITLE
Configuring available currencies in the `CONFIG` is not reversible

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#2161]
Running a script such as
```js
Hooks.once("setup", function(){
  const data = {
    hg: {label: "Heartnergold", abbreviation: "hg", conversion: 0.25},
    ps: {label: "Pansun", abbreviation: "ps", conversion: 2},
    cd: {label: "Credits", abbreviation: "cd", conversion: 200}
  };
  foundry.utils.mergeObject(CONFIG.DND5E.currencies, data);
});
```
does not immediately display any added currencies on the character sheet. Secondly, if one was to later remove currencies, the input fields never disappear, only labels do, and the sheet looks like this:

![image](https://user-images.githubusercontent.com/50169243/217110146-7abcccf0-5629-4552-80e6-d99de34a7208.png)

**Comment by arbron** [comment]
This is because we don't have a `prepareBaseCurrencies` method similar to what we are doing with skills and abilities to ensure that the proper values are available in character data. I have some plans to try and rework this functionality into the new `MappingField` so that should make it easier to get this working properly.
