### ISSUE TITLE
Consider dropping support for two core versions for future updates

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#2321]
With system updates generally causing breaking changes, with system support for both v10 and v11 it will not be feasible for module developers to move on to v11 exclusively as the system will cause issues with their modules in v10. It is also not possible for them to make a 'closing release' for v10 for their module when it is not known what could change for v10 users in the future in regards to the system.

I don't think it should be expected that all module developers run both v10 and v11 to ensure that their code works across all core versions.

**Comment by EvilRenegade** [comment]
I have nothing to do with anything and I'm just passing by coincidentally, so maybe the developers will see this differently - but: Not everybody can update at the same time. Especially not when major version updates in Foundry come with long lists of potentially breaking changes and things you need to be aware of.  
And modules which haven't been upgraded yet.

The last two times, my own upgrade to the next major was delayed by _months_, because I was certainly not risking breaking Foundry right before games, and I couldn't upgrade until all modules were available for that version.

So while you are absolutely correct that nobody can _expect_ module developers to support two versions, you are running into a chicken-and-egg issue here: People won't upgrade until the next major is fully supported, and while people haven't upgraded, there's still a large player base on the old version that'll need support.

Just as you can't expect developers to support two versions, you cannot expect game masters to drop everything and upgrade their stack _right now_.

Especially considering that there's no guarantee every single module developer actually got around to updating or even intends to update their module for the next major version.

So you're not _wrong_, but you're assuming a false ideal where every module is up to date on release day and all GMs have no obstacle and nothing better to do than updating Foundry right then and there. 

Dual support for the current and the previous version is widely common in commercial software development.  
Commercial software developers are motivated by hundreds of thousands of Dollars of costs to stop that.  
And it's still common.  
Because in reality, you're not gonna get your entire user base to update in a week.

Yes, you can still just decide to drop support anyway.  
But that just leaves a large part of your user base unsupported and pissed off.  
Which is generally not a desirable state of affairs.

**Comment by krbz999** [comment]
To clarify, it would be for future updates. Not retroactively making 2.2 or earlier versions non-functional on v10.

**Comment by Fyorl** [comment]
> I don't think it should be expected that all module developers run both v10 and v11 to ensure that their code works across all core versions.

It's not expected. Modules are not required to match the compatibility of systems. If a module author does not wish to support both v10 and v11, they can set their module's compatibility minimum to 11 to prevent the module being installed on v10.

**Comment by krbz999** [comment]
> > I don't think it should be expected that all module developers run both v10 and v11 to ensure that their code works across all core versions.
> 
> It's not expected. Modules are not required to match the compatibility of systems. If a module author does not wish to support both v10 and v11, they can set their module's compatibility minimum to 11 to prevent the module being installed on v10.

The system may still backport breaking changes. This happened with a module of mine already for example where the v10 version of it rendered several UI elements non-functional (due to `abilities` in the config becoming an object no less).

This means that users on v10, using the v10 version of a module, can receive breaking changes that such a module cannot not be updated to fix unless the dev *should* be expected to manage two core versions.

**Comment by Fyorl** [comment]
This is what the `verified` and `maximum` fields of the system relationship is intended to be used for.

**Comment by EvilRenegade** [comment]
Just to emphasize my own point: I finally got around to upgrading to v11 _yesterday_.  
And looking at the release dates of previous releases, that may very well mean that I basically missed the entire v11 release cycle and the next update will be yet another major release update.  
Which I won't get around to quickly either, because I'm not potentially breaking the world right before a game.

There are several add-ons which could no longer be updated beforehand because they required v11, and there are one or two which cannot be used now because they're not v11-compatible.

As long as you have an upgrade procedure as involved and destructive as Foundry's, you more or less have no other choice but to either support two versions, or to accept that part of your users will be unhappy.

Obviously, it would be reasonable for **module developers to petition for API versioning** and/or feature flags instead.

i.e. encourage the Foundry devs to place the api under an api-object to be queried with a version number, and to commit to that version remaining stable and supported for n+2 versions.  
That way, you can code your module against `api[11].game.foo`, it'll still work when v12 is out, and you can migrate from `api[11].game.foo` to `api[12].game.bar` in your own time. 

Or `api.v11.game.foo`.  
Or `getApi(11).game.foo`.

Doesn't matter how they do it.  
Stable, versioned APIs which are supported for at least three Foundry versions would solve the problem for both module developers as well as end users.

Now you just need to convince the Foundry devs.
