### ISSUE TITLE
WebGL Context can be lost while setting Dice Scale Values

### ISSUE THREAD

**Issue by MaxPat931** [foundryvtt/dnd5e#2371]
Can take a few attempts to reproduce, but it seems to happen after typing a value in the Count column and then clicking the Dice dropdown. When you click focus out of the Count column the Advancement and Class items refresh, cancelling the dropdown, and at some point it can lead to a webGL context loss.  
I fear this could also affect other fields that rely on others being updated, such as an Item's Target  fields, although it may only become a problem if you're updating several of those fields quickly?

Recording in v11.305, Dnd5e 2.2.2

https://github.com/foundryvtt/dnd5e/assets/86370342/cde592b6-c2ef-433f-8e8d-e9531c27132d

Was also able to repro in the Demo database, v10.291, Dnd5e 2.1.5, with an error as well
![image](https://github.com/foundryvtt/dnd5e/assets/86370342/48e41cb6-1d0b-4158-a9c9-ee00aaa74c31)

All tests on Chrome

**Comment by MotoMoto1234** [comment]
I too can reproduce this with no modules active in v10.303 and v11.305.  This window seems to have some sort of flaw in the way the drop down works or something for the dice size.

**Comment by MotoMoto1234** [comment]
I can now also replicate this while trying to rapidly create an item from scratch in dnd5e 2.2.2 v11.305.  Its not just this window.  It has to do with changing many drop down values in succession with high precision clicks.

**Comment by MotoMoto1234** [comment]
I feel confident that the cause of this bug is users using chromium browsers and having the chrome://flags set to override "GPU rasterization".  Its default usually, so I think possibly if you have users turn on hardware accel, some drivers might utilize this and cause it?  I personallly had it on and was able to stop this bug by resetting it to default.

**Comment by fylson** [comment]
I got the exact same issue when i am using the foundry.exe. I can provoke it, if i am open some drop-downs in items or other things. 

Did someone find a proper fix? (dnd5e 2.3.1 - v11.313)

**Comment by MotoMoto1234** [comment]
Its an insidious bug that is hard to repro.  Even after tweaking chrome flags it still happens, easiest way to repro it is in the scale value setup menu since its 90% drop down menus but when this crash happens its **always** when trying to change a drop down entity.  I get it alot in item sheets in dnd5e too.

**Comment by fylson** [comment]
I made some tests. It even happens in Chrome and in the foundry client (wich is basicly chrome too). I cannot reproduce the bug in firefox and opera (both works fine).

**Comment by MotoMoto1234** [comment]
The three most supported browser clients are the foundry app, chrome, and edge and if its happening on those I'd imagine they need to figure it out lol.

**Comment by fylson** [comment]
yes, afaik they are all chrome based. The issue is in chrome, but is it dnd or foundry itself? Not tried (right now) in other game systems.
