### ISSUE TITLE
Remove hard dependency on an active effect's parent for item sheets

### ISSUE THREAD

**Issue by DFreds** [foundryvtt/dnd5e#2375]
My module Convenient Effects allows active effects to exist outside of the scope of an actor or item. This means that they don't have parents.

This code is causing an undefined type error. https://github.com/foundryvtt/dnd5e/blob/797d0bc700ee9c9b1567b6c4e53de1e1f671dbc8/module/applications/item/item-sheet.mjs#L576

See https://github.com/DFreds/dfreds-convenient-effects/issues/268 as well.

I recommend either doing some nullability check on the `effect.parent.uuid` or something similar.

**Comment by Fyorl** [comment]
I will assign this to 2.3 since it's easy to change, but ActiveEffects are not primary Document types, so there are possibly other places in both the system and core that (rightly) assume any given ActiveEffect has a parent. The same would be true for TableResult, Card, or Combatant, etc.

Without having inspected the module, I'd guess you're probably instantiating ActiveEffect instances from some JSON, or maybe hardcoded data? You could try also instantiating a 'fake' parent for the ActiveEffects (probably an Actor to avoid triggering transfer logic). That might resolve this issue, and perhaps avoid errors elsewhere, but it might also create some other problems; I'm not sure without trying it.

**Comment by DFreds** [comment]
You're correct, and I'm aware. Yes, I am treating them as basically docs without parents and instantiating them from hard-coded objects. If I set their parent to a fake Actor or something, I think that would break a large part of the integration with modules like midi-qol who check for those types of things. 

I appreciate the response though. If it's possible to just add the null check, I could go from there.

**Comment by tposney** [comment]
Not sure if it's relevant but foundry has exactly the change requested when dropping an effect onto an actor.

If I understand the code the check is simply to stop dropping an effect from an actor/item onto the same item/actor and the effect is immediately created with a valid parent set.
