### ISSUE TITLE
Add "search/filter on name" bar to character sheet Spellbook tab

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#243]
Originally in GitLab by @TheGiddyLimit

As per title, it's currently pretty annoying to wade through a big spell list.

**Comment by niaeashes** [comment]
Can I try it?

**Comment by aaclayton** [comment]
> Can I try it?

Yeah, certainly. I think the biggest source of controversy here that we'll want to get alignment on at first is going to be the final UI, because the underlying "how" is relatively straight forward. Foundry VTT provides a search filters abstraction that we can use for items/spells/feats/etc.... but the UI will be a bit crowded and making sure that the UI/UX looks good is going to be the biggest portion of the battle here. 

My advice would be to start with some UI/UX mockups so we can agree on that before writing the JS code.

**Comment by niaeashes** [comment]
Understood. Now I will think about the UI proposal.

Can I post my proposal as a comment on this Issue?

**Comment by aaclayton** [comment]
Yeah, we can discuss some UI/UX proposal as part of this issue before proceeding.

**Comment by niaeashes** [comment]
I know it's late, but I have a UI suggestion. This proposal is based on release-2.0.2.

First I will write an analysis of the current Spellbook tabs.

The current Spellbook tabs are a bit confusing due to the space-saving nature of the tabs; Let me point at the HTML structure to better explain this. The .spellbook-filters tag encompasses the system.attributes.spellcasting select box. This is problematic not only from a markup point of view on the HTML, but also (in my opinion) slightly counter-intuitive to the user.

<img width="742" alt="Screen Shot 2022-09-04 at 12 59 30" src="https://user-images.githubusercontent.com/1019357/189469387-3de994c6-aeb0-4a71-b42b-dacbd2ec0434.png">

Filters are a feature that supports browsing, and the select box for the Spellcasting attribute is actor data. This is a different UI with a different purpose. I believe they should be split by their purpose.

The gist of my proposal is to move the select box for the Spellcasting attribute to another row and add a text box to the filter. Moving the select box creates enough space for the text box.

<img width="761" alt="Screen Shot 2022-09-04 at 13 23 01" src="https://user-images.githubusercontent.com/1019357/189469395-b3adbae2-6ed6-4d41-8bbe-d5dadb2f8d08.png">

I have not adjusted the detailed CSS style of the UI.

The problem of this proposal is that the UI will occupy one more row.
