### ISSUE TITLE
Reimplement 'None' as a valid activation type

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#2465]
Previously "None" was a truthy value, which easily served this purpose, allowing for creation of items with ranges, limited uses, etc., but nowadays 'Special' is the best fit.

However several actions are very clearly labeled as not requiring any action where 'Special' shouldn't need to serve as a catch-all.

**Comment by Fyorl** [comment]
This is a little bit of an unfortunate situation. I think if I were to read a feature that said 'no action required' and then look at how to input that on the sheet, then 'Activation Cost: None' would make the most sense to me. Perhaps we should go back to having a blank option and a 'None' option separately? It's not something I considered at the time.

Since 'None' currently unambiguously means 'this item cannot be activated', it should not even require a migration, we just change the label of `activation.type: ""` from `"None"` to `""` and re-add the separate `"None"` option.

**Comment by krbz999** [comment]
An empty option would also fit in with how Action Type below is blanked out.

However we should consider hiding the cost field for the activation type for some of the types (eg "3 Special" or "1 None" makes very little sense).

(... Well actually just those two, but it's a config object, so users can add more.)

**Comment by Fyorl** [comment]
> However we should consider hiding the cost field for the activation type for some of the types (eg "3 Special" or "1 None" makes very little sense).

That sounds reasonable to me.
