### ISSUE TITLE
Allow DMs to 'forward' a roll prompt to connected clients

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/dnd5e#2513]
Related #2461, #1865, #2138

Some context: Typically the DM will be reading the adventure journals that call for certain rolls and clicking the 'DC 20 Dexterity (Acrobatics) check' box, but it's the players that need to actually roll.

Some suggestions:
1. Clicking an enriched link spawns a roll dialog as normal. The DM can then 'forward' it directly to connected clients. Optionally the DM can configure something like the ability to use and 'force' the clients to use those options.
2. Allow any sort of chat card spawned by a roll (particularly from the DM) to have a context-menu option to forward the roll to connected clients.

**Comment by MaxPat931** [comment]
Perhaps appending a "Send to chat" option onto the enriched links, similar to how pf2e handles this, would be another option?
![image](https://github.com/foundryvtt/dnd5e/assets/86370342/c86e65d5-11b7-4f69-bb65-cd36d07a4a9e)

**Comment by arbron** [comment]
I've been working on a prototype similar to Max's suggestion:
<img width="199" alt="Screenshot 2023-10-23 at 14 27 24" src="https://github.com/foundryvtt/dnd5e/assets/19979839/97028e0a-e320-4a1a-8e34-2122e6842ebf">
(this only shows up for GM users)

Which just throws a simple prompt into chat:
<img width="295" alt="Screenshot 2023-10-23 at 14 28 16" src="https://github.com/foundryvtt/dnd5e/assets/19979839/b1bab435-e544-43fe-858d-475ffcd0b02d">

I was thinking that there is a possibility of a dialog in the process for a few things:
- Providing a DC if one isn't provided, or tweaking an existing DC
- Hiding/showing the DC (perhaps default controlled by system-level setting that would also affect DCs from NPC items)
- Only requesting from certain players, displayed as a whispered roll

If this request interface is made robust enough, it could potentially also be adapted for requesting a roll out of the blue rather than just from chat.

**Comment by MaxPat931** [comment]
I think this can be closed?
