### ISSUE TITLE
Use the new active effect transferal mode

### ISSUE THREAD

**Issue by kaelad02** [foundryvtt/dnd5e#2564]
Foundry v11 introduced a setting, `CONFIG.ActiveEffect.legacyTransferral`, that when set to `false` will use a new mode of transferring active effects from embedded items to their actors. Instead of copying the active effect document from the item to the actor, the actor uses the copy of the active effect that's on the item. This will improve the user experience since editing the active effect of an item already on an actor is error prone and often requires re-adding the item to get it to work correctly.

This will require making Foundry v11 the minimum version, which is probably why it wasn't done already. It's just a one-line change in the main `init` hook but could have other implications. The one I can think of is how to show the transferred active effects on the character sheet. Meaning, do we want to indicate somehow the difference between active effects that were created directly on the actor vs those from an item? Maybe we don't bother, but I figured I would bring it up.

**Comment by krbz999** [comment]
Currently we browse through `actor.effects` when preparing them for rendering on the actor sheet. This could be changed to `actor.allApplicableEffects`, which would return a generator for all effects on both the actor and their items that target the actor at all (disabled, unavailable, or otherwise).

The main tasks would be having a migration in place to delete current effects on actors when or if they exist on their items already, if that is something we would want to do. Secondly rendering them on the actor sheet correctly (possibly appended with the item's name), and lastly changing the hotbar macro to be able to target grandchild effects.

Good chance this would fix https://github.com/foundryvtt/dnd5e/issues/2459 too; with legacy transferal disabled, we can assume that if an effect is originating from elsewhere (not the actor it is on, but possibly one of its items), then it has been added manually and shouldn't need to be suppressed, and any effects on items can incredibly easily be shown as unavailable/suppressed simply by checking the state of their parent item.

**Comment by kaelad02** [comment]
This was done in version 3.0.0
