### ISSUE TITLE
Remove Background/Race Type Limitations

### ISSUE THREAD

**Issue by webmaster94** [foundryvtt/dnd5e#2621]
For what reason has a restriction been arbitrarily added on the number of backgrounds. I use multiple backgrounds on characters to use the advancement systems for custom add-ons to D&D 5e such as Level up (Advanced 5th Edition). This change seems to remove homebrew capability for no real reason. Additionally, I can only assume this restriction has been placed on the new Race Type. This will prevent a popular homebrew of splitting physical race and upbringing, implemented in A5e as Heritage & Culture and upcoming implementation in D&D as Ancestry & Culture.

**Comment by arbron** [comment]
My feeling on this is now that v11 supports custom module types, these homebrew options would be better served by adding in proper item types rather than abusing the existing system.

More technically, on races in particular, because of the way that sense, movement, and creature type are applied to the actor it isn't possible to support multiple races.

**Comment by webmaster94** [comment]
I don't see why you can't simply disable certain aspects that are
automatically added by the race type. Also, that doesn't really address the
background issue. In the previous version. Backgrounds could be added with
no issue to the advancement system.
