### ISSUE TITLE
Original Source field shows broken links

### ISSUE THREAD

**Issue by M0nk3yy** [foundryvtt/dnd5e#2642]
If I want to make a new feature and decide to do so by cloning a tangetially similar feature, I am left with a permanent reminder of which item was cloned in terms of the "Original Source" field:

![image](https://github.com/foundryvtt/dnd5e/assets/66137312/b3d12c22-c8e8-4232-8740-f09ee175abc0)

It is quite hidden away, so is not a big deal, but I do think that I should have control over this. Currently it cannot be deleted or edited in any way.

The other common scenario I am facing is this:

![image](https://github.com/foundryvtt/dnd5e/assets/66137312/9598df52-eb05-45f2-840d-8bc341108e1b)

where "undefined" links populate the field. Again, I cannot manually add a new source, or remove the broken link. In the case of this particular example, it is because I imported this actor between Foundry instances and the source is not available in the new world.

I would suggest that the most ideal solution would be formatting this section as in Advancements, so they can be deleted or new sources added via drag and drop.

![image](https://github.com/foundryvtt/dnd5e/assets/66137312/f53f8481-a72e-4a3d-bd62-5c70ba089804)

In the meantime, I am removing the links via macro (thank you @krbz999).

`(await fromUuid("<uuid goes here>")).unsetFlag("core", "sourceId");`

**Comment by Fyorl** [comment]
The `core.sourceId` flag is API-only and not intended to be user editable. We also don't expect that the average user will be editing the source information for their Items, it's primarily intended for content providers. We should fix the display of broken links, but other than that I don't anticipate we would make additional changes here just yet.

**Comment by M0nk3yy** [comment]
So if an item is cloned, it is considered intentional that the source shows the original item and it cannot be altered?

**Comment by Fyorl** [comment]
The `sourceId` flag has always been managed by the core software and simply putting it on display somewhere in the UI in a game system hasn't changed that.

It's unclear what you mean by 'cloned', but `Document#clone` does not set the `sourceId` flag, and therefore by extension duplicating an Item via the context menu command also does not set the `sourceId` flag. It's set under a few different circumstances (I may have missed some):
1. Importing an Item from a compendium.
2. Copying, cloning, or otherwise duplicating an Item that already had a `sourceId` flag will inherit the same `sourceId` as the original Item.
3. Dropping an Item from the sidebar onto a sheet will set a `sourceId` provided the original Item did not already have a `sourceId`, otherwise it will behave per (2).

**Comment by krbz999** [comment]
4. Dragging an item but dropping it in the same location (this sets it locally and vanishes upon refresh).

**Comment by M0nk3yy** [comment]
Yeah, probably improper terminology on my part. The SRD items (at least once imported) appear to have their own item name set as the source (whereas freshly created items are entirely blank). Upon duplicating the item (right-click, duplicate), the original item is then permanently recorded as the source.

Having this reminder permanently embedded with no way to change it doesn't seem proper in my opinion.

**Comment by krbz999** [comment]
I don't think there's a misunderstanding here, but rather a request, i.e.: "I want to make a new feature and decide to do so by cloning a tangetially similar feature," and thus Chronurgy has 'School of Evocation' as its source. Which seems quite useless, perhaps even misleading.

**Comment by Fyorl** [comment]
I understand the request, but I already answered it [here](https://github.com/foundryvtt/dnd5e/issues/2642#issuecomment-1829863426). There are no plans to allow the `sourceId` flag to be user-editable at this time.
