### ISSUE TITLE
SRD Monster Actions Descriptions Not Working

### ISSUE THREAD

**Issue by DMBobS** [foundryvtt/dnd5e#2854]
When I open an SRD Monster sheet, I can no longer click on any Actions, Attacks, Inventory items, or Spells to get a description, or to initiate a random roll in the chat messages display. This was a tremendous capability in the previous version, so I don't have to calculate and type in each attack roll.

**Comment by schultzcole** [comment]
@DMBobS could it be that the actor you are using has not yet been imported into your world? Rolling directly from the sheet is disabled for actors that are being previewed from a compendium but should work as expected for actors that are imported.

**Comment by Fyorl** [comment]
We seem to have regressed here. It *should* be possible to roll from an Actor inside an *unlocked* compendium (if maybe inadvisable). When I checked, it seemed to not be possible. Rolling from a locked compendium can't be supported since doing so may require updates to the item (in cases of limited use consumption for example).

**Comment by JPMeehan** [comment]
This seems to seriously blur the line between the role of in-world actors and the deep storage functionality of compendiums

**Comment by arbron** [comment]
I blocked a few paths from rolling within compendiums intentionally because we use `fromUuidSync` in several places for activities, which doesn't work for actors in compendiums. If we really wanted to support this we'd have to do an audit of all of the new activity usage stuff to remove any usage of `fromUuidSync`.

**Comment by krbz999** [comment]
Actors and items in compendiums really should not be used, 'tis a silly notion.

**Comment by Fyorl** [comment]
OK, it sounds like it's more trouble than it's worth then.
