### ISSUE TITLE
Some Starter Heroes still use legacy resources

### ISSUE THREAD

**Issue by Sillsoft42** [foundryvtt/dnd5e#2890]
It looks like that the old resources which are added to the favorites section on the new character sheet with 3.0 are unclickable.

I tested this in a fresh world with no modules running and taking a look at the Krusk starter hero.  The Lay of Hands that shows up in the favorites automatically isn't clickable but if I drag a new one there, it works.

**Comment by Fyorl** [comment]
It's because resources are not items, they're just data that exist on the character. It sounds like you deleted the Lay on Hands resource and replaced it with the Lay on Hands item, which is the recommended thing to do.

The Starter Heroes shouldn't use the legacy resources though, so I will repurpose this issue to fix that.

**Comment by Sillsoft42** [comment]
Thank you.
