### ISSUE TITLE
Allow for the list of targets to be collapsed in attack roll messages and to determine which token is which target

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#2892]
Would be useful if massive lists like these, rare as they are, could be collapsed or each individual entry be a bit smaller. Likewise would be good if there was a way to determine which target is which (eg click to pan or click to select). The names seem to be the actor name, rather than token names.

![image](https://github.com/foundryvtt/dnd5e/assets/50169243/036aec83-116f-45c0-8dfe-a22884d88b91)

**Comment by GamerFlix** [comment]
The ability to select the token would further allow for easy damage application, especially if a way of selecting the token without dropping previous selections is available.

**Comment by MaxPat931** [comment]
Being able to select the speaker of a Saving Throw chat card would also be helpful

![image](https://github.com/foundryvtt/dnd5e/assets/86370342/2f5a87ff-4e00-4cde-8478-cb66f6f01387)

**Comment by krbz999** [comment]
Going a step further, the ability to apply damage (or healing or temp hp) with a right-click on an *attack* roll should be removed. This could be substituted with new context menu options that select all targets that were hit or missed (two options).

**Comment by Fyorl** [comment]
The initial implementation was just for attack rolls in order to allow this design work to be postponed, but it does need to be solved eventually for things like the targets of AoE spells. Some combination of a scrollable container + collapsing is the most straightforward but we could look at some other solutions such as utilising popout chat cards, or even tooltips maybe.

**Comment by arbron** [comment]
Partially solved by Zhell's PR, remainder is being solved with https://github.com/foundryvtt/dnd5e/pull/3405
