### ISSUE TITLE
Items with `uses.value` or `uses.max` filled in but not `uses.per` still show as limited uses on the character sheet. If a feature instead has 'recharge', this does not show at all under any circumstances

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#2930]
Tested with a feature item.

**Comment by Fyorl** [comment]
The 1d6 recharge mechanic is exclusively for NPCs, so there was deliberately no time spent on it for the character sheets. I expect it will come back purely via code-sharing with the NPC sheets though. That was probably the reason we used bespoke logic for detecting limited uses rather than using `Item5e#hasLimitedUses`.

**Comment by Hoppyhob** [comment]
I can work on this.
