### ISSUE TITLE
AEs explode on migration to 3.0.1

### ISSUE THREAD

**Issue by itteerde** [foundryvtt/dnd5e#2934]
AEs explode on migration to 3.0.1

https://discord.com/channels/170995199584108546/670336046164213761/1204435692977918092

**Comment by Fyorl** [comment]
Can you post the Actor's UUID (right-click the book icon next to the character's name in the title bar), as well as the `origin` values for each of the Comprehend Languages and Disguise Self effects?

**Comment by itteerde** [comment]
`Actor.XbezijMrVTRuOmFc`
```js
[
    {
        "name": "Comprehend Languages",
        "origin": "Actor.XbezijMrVTRuOmFc.Item.ozjZadHlZOnEWP4P"
    },
    {
        "name": "Lamp",
        "origin": "Actor.XbezijMrVTRuOmFc.Item.YSqIuD4NIO3jRJmt"
    },
    {
        "name": "Comprehend Languages",
        "origin": "Actor.XbezijMrVTRuOmFc.Item.ozjZadHlZOnEWP4P"
    },
    {
        "name": "Detect Magic",
        "origin": "Actor.XbezijMrVTRuOmFc.Item.YbmATedSdUh1PxqQ"
    },
    {
        "name": "Disguise Self",
        "origin": "Actor.XbezijMrVTRuOmFc.Item.p27xtZCilZ12ixm5"
    },
    {
        "name": "Expeditious Retreat",
        "origin": "Actor.XbezijMrVTRuOmFc.Item.y1eNMIMfG5vx4C5C"
    },
    {
        "name": "Jump",
        "origin": "Actor.XbezijMrVTRuOmFc.Item.LPhQ9s5WsYXRrR1j"
    }
]```

**Comment by arbron** [comment]
I wonder if this is an issue with the times on the effects. The migration script that detects duplicates does a diff between the effect on the item and on the actor, so if the times have changed then it might result in them not being identified as duplicates.

**Comment by MotoMoto1234** [comment]
Midi is about to release 11.4.1 which will have dnd5e 3.0 compatibility.  You are about to get an influx of users who will migrate and have an absolutely large amount of duplicate active effects caused by this bug.  This happens 100% of the time in a world migrated.  In Midiqol there are significantly way more active effects than a core world.  While I understand it a module, this is a migration script bug that is duplicating these ae's.  Is there an eta on fixing this?  You are about to have a pretty hefty chunk of users about to update to 3.0 and its going to basically break worlds because it is really tedious to go through 6000 monsters/actors to clear duplicate ae's.

**Comment by tposney** [comment]
when you say it does a diff, does that including flags? For non-transfer/passive effects midi/dae will create flags on creation of the effect on the actor, so a straight diff won't work.

It probably makes sense for me to write module specific de-duplication rather than you having to guess what changes if any midi/dae have done.

**Comment by itteerde** [comment]
Well, I am not using MidiQOL or DAE. There is some chance that there is a DDB cause, but I think some AEs affected are hand made.

**Comment by krbz999** [comment]
Surprised that script didn't fail for a lot of users when `origin` can be `null`.

**Comment by krbz999** [comment]
It looks just at `changes`, my guy.

**Comment by MotoMoto1234** [comment]
This is the 2.4.1 actor before migration:
![image](https://github.com/foundryvtt/dnd5e/assets/116308065/a7c2b175-40b7-42d5-b6af-87eff88a24c1)


This is the 3.0.2 post migration actor(disregard the NaN's that bug is squashed by tposney already)
![image](https://github.com/foundryvtt/dnd5e/assets/116308065/b73e1e51-8f43-4c17-8aae-ce241f4a9817)

There are no errors in the migration process at all, I ran the migration in safe configuration mode.

**Comment by arbron** [comment]
So one potential issue is that the de-duplication migration is only run on actors that haven't yet been modified in `3.0.0`, so it checks the `_stats.systemVersion` and doesn't run anything unless it is older than that

**Comment by itteerde** [comment]
I would have to do further investigation, about maybe having old modules stuff on the AEs, but I am migrating 2.4.latest to 3.0.2 and it still duplicates.

**Comment by arbron** [comment]
Looks like there is an issue with how deleting effects combines with the `persistSourceMigration` flag.

**Comment by arbron** [comment]
PR is up, feel free to test it to see if it fixes migration issues: https://github.com/foundryvtt/dnd5e/pull/3061
