### ISSUE TITLE
Custom elements lose styling when moved between hosts

### ISSUE THREAD

**Issue by lphillips** [foundryvtt/dnd5e#3044]
The `dnd5e 3.0` system is no longer compatible with the PopOut! module. The character sheet relies on various CSS and Javascript features that make it incompatible, causing rendering issues that make the sheet unusable in a pop out window. Details can be found in this issue report in the PopOut! repo: https://github.com/League-of-Foundry-Developers/fvtt-module-popout/issues/109

I know that there's no guarantee of compatibility with any given third-party module, but the ability to pop out a character sheet or journal entry to a separate window helps a lot with managing all the characters and notes you have when running or playing the game. If it's not feasible to maintain compatibility with PopOut! then it would be great to have the ability to open a character sheet in a separate window be part of the `dnd5e` system.

**Comment by Ator27** [comment]
I updated because the new dnd5e 3.0 just looked so cool.  Sadly, I will continue to set the default to the character sheets to the old sheets because people use the popouts so much. Maybe I'm overstating this and maybe I'm also in the minority, but I really think making this update work with popout module should be considered.

**Comment by Vengrath97** [comment]
+1

**Comment by guldelox** [comment]
+1 This module was very useful in streamlining workflow during a game and preventing people from having to hunt through windows and journals and sheets. Definitely a Quality of Life thing that ideally would be core Foundry functionality, but it's understandable that it may need to be done at the System level rather than Core.

**Comment by schultzcole** [comment]
Looping in #3048 for posterity's sake
