### ISSUE TITLE
[feature request] allow for sorting the spells by spell level

### ISSUE THREAD

**Issue by rapus95** [foundryvtt/dnd5e#3052]
I'm playing a resource caster which doesn't use ordinary spell slots but a resource (item). The spells take up that resource in the same amount as the level of the spell. In order to not have to fiddle with spell slots, I configured all these spells with their respective spell level and "Innate spellcasting". But within that category there's no level sorting. This requests to allow for sorting by level within the respective categories. As a third option on the same level as "sort alphabetically" and "sort manually".

Furthermore it would be nice if there was a column or place which shows the individual spell's level.

**Comment by Zanderaf** [comment]
Spellcasting is generally still a big work in progress, and something like this (Sounds similar to a Spell Point system) is 100% possible but the work around of a spell needing to be innate is wonky I'll give you that. From what I remember there was no real need to sort Innate spells because Innate normally assumes no upcasting iirc. You cast your Innate spells innately at their base level and what not.

Something like Spell Points could solve something like this, making a custom version of a spell-point spellcasting progression for a specific class,. Though it is far off and we've still yet to have a PR published for a Spellcasting Advancement to spruce up the whole spellbook system.

**Comment by rapus95** [comment]
@Zanderaf I also came to the conclusion that "something like spell points" could help solving this, which lead me to create yet another feature request which points to all the advantages I guess: https://github.com/foundryvtt/dnd5e/issues/3053
