### ISSUE TITLE
System tooltips render incorrectly with `data-tooltip-direction="UP"` and `="DOWN"`

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#3071]
Edited manually in console to add the dataset properties.

DOWN renders identically to `LEFT`.

UP renders like so:
![image](https://github.com/foundryvtt/dnd5e/assets/50169243/ad6496b1-02e5-48da-b9d4-5659e9f74ded)

**Comment by Fyorl** [comment]
Item tooltips don't really respect direction. That was because they needed to render either left or right of an item in order to not obscure the information beneath them. This 'hard-coding' was never cleaned up after the proof-of-concept stage, but they should probably respect the `tooltip-direction` and we add `tooltip-direction`s to the item tooltip source elements instead.
