### ISSUE TITLE
Redesign NPC sheets for v2 design like Character sheets

### ISSUE THREAD

**Issue by SirAron111** [foundryvtt/dnd5e#3093]
Monster and NPC sheets don't have the same design as as the Character sheets.
Would be nice to get the same design layout for NPCs as for PCs.

**Comment by Zanderaf** [comment]
It was mentioned as Work in Progress during the big 3.0 reveal, most of the system's interfaces I think are gonna be redesigned, the player sheet was just the first big thing they did. (Dont quote me on anything I may be 200% wrong)

**Comment by Rabulias** [comment]
Would this be a good time to incorporate Short and Long Rest buttons on the NPC sheets? (Ticket [495](https://github.com/foundryvtt/dnd5e/issues/495))

**Comment by nschoenwald** [comment]
As a GM, I would love to have the option of always having all text for NPC features, attacks and actions visible, similiar to how official statblocks in the books or on DnDBeyond look. Having to click every single feature to read it in the middle of battle makes it much more likely to miss crucial information when running encounters.
It would be great if this was the default or at least an option in the new NPC sheets. The way [monster blocks](url=https://foundryvtt.com/packages/monsterblock/) displays stat blocks is perfect when running encounters, it would be great if the redesign could take some inspiration from that.

**Comment by Rabulias** [comment]
Possible related suggestion: Ticket [1103](https://github.com/foundryvtt/dnd5e/issues/1103)

**Comment by guldelox** [comment]
> As a GM, I would love to have the option of always having all text for NPC features, attacks and actions visible, similiar to how official statblocks in the books or on DnDBeyond look. Having to click every single feature to read it in the middle of battle makes it much more likely to miss crucial information when running encounters. It would be great if this was the default or at least an option in the new NPC sheets. The way monster blocks (https://foundryvtt.com/packages/monsterblock/) displays stat blocks is perfect when running encounters, it would be great if the redesign could take some inspiration from that.

Absolutely agreed, having npc sheets value function, speed and ease-of-use overshadows any beautification considerations for me as a DM.

**Comment by Zanderaf** [comment]
Is there a chance we could maybe keep an option to always display a list of skills in NPC sheets? Personally useful for me when I have players forcing skill checks onto other creatures, and having just a list I can quickly check would be nice.

That and it sometimes is hard to remember what skill goes with what stat, even though they can be changed.
![image](https://github.com/foundryvtt/dnd5e/assets/65571170/0d67d8dd-1d70-40fd-b6f1-5de5dc7ea919)

**Comment by etiquettestartshere** [comment]
I also would prefer it it did not become API only to roll skill checks in non-proficient skills for npcs. In roleplay heavy environments (or stealth heavy environments), npcs rolling skill checks in non-proficient skills is a common occurrence.

**Comment by Fyorl** [comment]
> bonuses to particular skills that said npcs are not proficient in are less common, but not an impossibility

I think 'less common' is perhaps overstated. I would expect that cases where an NPC has an external bonus to a specific skill (i.e. not ability checks in general) that they are not proficient in, and that bonus is not advantage/disadvantage (as they are not handled by the system anyway), are almost non-existent. Do you have any examples?

**Comment by krbz999** [comment]
Opposing a grapple, making a stealth or perception check, or similar recurring (specifically skills) checks.

While a standard ability check could stand in for these, it voids any automation that are making use of, for example, the `dnd5e.rollSkill` hook.

**Comment by Fyorl** [comment]
> Opposing a grapple, making a stealth or perception check, or similar recurring (specifically skills) checks.

I understand the cases where an NPC might need to make an ability check with a skill they are not proficient in, but that was not what I asked.

**Comment by Zanderaf** [comment]
Making an Investigation check in specific is also part of some spells
"the creature can determine that it is an illusion with a successful Intelligence (Investigation) check against your spell save DC."

The only one that really comes to mind as quick as I can, but I guess that just rolling Intelligence would work, but just feels a bit weird in cases where there are things that the creature benefits from that specify Investigation in terms of active effects.

**Comment by Fyorl** [comment]
Again, I understand the cases where an NPC might need to make an ability check with a skill they are not proficient in. Rolling the plain ability check without the skill will give the same result and is equivalent in game terms. Exceptions to this are when the NPC has a bonus that affects ability checks made with a specific skill. To address this. we discussed a way to configure a skill to be visible on the NPC sheet even without proficiency (similar to how tools work), but it was de-prioritised.

> in cases where there are things that the creature benefits from that specify Investigation in terms of active effects

And I am asking for examples of this that come up in normal play, preferably with official content, in order to gauge the priority of this feature. NPCs with bonuses to specific skills that they are not already proficient in are very rare, and, of those, bonuses that are not advantage/disadvantage are almost non-existent as far as I can tell. The only one I can think of off the top of my head is the +10 bonus to Stealth from Pass without Trace that a friendly NPC travelling with the party might occasionally benefit from.

**Comment by Zanderaf** [comment]
- The only other one I can think of in such short notice is Gloves of Thievery: "While wearing them, you gain a +5 bonus to Dexterity (Sleight of Hand) checks and Dexterity checks made to pick locks." Namely the first part of the item with SoH checks.

This all in mind, I've never been a fan of how WOTC stat-blocks displayed the skill bonuses, I understand that they take room in sheets, it just feels off and a bit weird not having that list there after having since NPC sheets were a thing for the system. 

As for when a NPC might need to make an ability check they aren't proficient in; I think that genuinely might be a campaign-by-campaign basis. The campaigns I run personally make use of that a decent bit but that's personal taste. Someone else might not make use of them at all, someone might use non-proficient skills sporadically. If its a situation of just "DMG, how the game is "meant" to be played" and "most npcs have no need of skills they aren't proficient in", then yea, I guess there's no real need of that constant list.

**Comment by Rabulias** [comment]
Most of the time showing only the NPC skills that have Proficiency is fine. Even for things like a magic item granting a bonus, it can be added once and left in place as it would be a rare case the NPC is not using the magic item. The problem comes up with spells or features that grant skill bonuses or impose skill penalties. The one that comes to mind for me is _pass without trace_ that grants a +10 to Dexterity (Stealth) checks. These might come up in a combat and not be "always on." I can't find it ATM, and it may be third party, but there was a monster that imposed disadvantage on Wisdom (Perception) checks, but not other Wisdom checks or savings throws.

**Comment by etiquettestartshere** [comment]
> Do you have any examples?

Raw? No, I have no examples. They may or may not exist. All I can say is that they exist in my own game.
