### ISSUE TITLE
CharacterSheet displays displays incorrect initiative bonus if AE is present

### ISSUE THREAD

**Issue by itteerde** [foundryvtt/dnd5e#3119]
CharacterSheet displays displays incorrect initiative bonus if AE is present

![image](https://github.com/foundryvtt/dnd5e/assets/8367477/aed0e569-41af-476b-8132-b378fa20e80f)

if there is an AE adding another Initiative Bonus the normal bonus is not displayed, if the AE is deleted the bonus is correctly displayed

**Comment by arbron** [comment]
That is specifically because you included a dice value in the initiative bonus. None of the bonuses on the sheet display if part of their formula includes non-deterministic values. Potentially we could modify how `simplifyBonus` works to include portions of the formula that are deterministic, but that would affect a bunch more than just initiative.
