### ISSUE TITLE
`@Embed[tableUuid]{custom caption}` displays both the custom caption as well the default table name in a content link

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#3231]
I would have expected this would replace the inner text of the content link.

![image](https://github.com/foundryvtt/dnd5e/assets/50169243/9280b4ca-c1ac-4b4e-9562-5140d051f81a)

![image](https://github.com/foundryvtt/dnd5e/assets/50169243/6af87a35-d9d2-4392-976f-f2a3193f7183)

![image](https://github.com/foundryvtt/dnd5e/assets/50169243/2b2fec98-ba75-483e-99c3-7f4dbdc888d0)

`cite=false` removes the table name. Doesnt seem to be way to customize it.

**Comment by arbron** [comment]
The text after the enricher changes the caption, not the citation name which is always the name of the item being embedded (specifically it is the item's anchor using `doc.toAnchor()`):

<img width="665" alt="Screenshot 2024-03-12 at 10 29 06" src="https://github.com/foundryvtt/dnd5e/assets/19979839/63543f78-728b-4852-b469-a896771ad349">

<img width="667" alt="Screenshot 2024-03-12 at 10 29 15" src="https://github.com/foundryvtt/dnd5e/assets/19979839/aa3338d2-8fc2-42a1-8cde-f8893d34a48b">

<img width="672" alt="Screenshot 2024-03-12 at 10 29 24" src="https://github.com/foundryvtt/dnd5e/assets/19979839/e04db7db-7d8e-447f-a672-f019298aee5a">

You could probably request a feature to customize the name on the citation, but you might want to file it with the core repo because once we go V12-only this code will be replaced with core's implementation.
