### ISSUE TITLE
Allow capacity multiplier to be customized & targeted by active effects

### ISSUE THREAD

**Issue by jtracey** [foundryvtt/dnd5e#3259]
I was trying to create an effect for Bull's Strength (one of the choices for the Enhance Ability spell), but it seems the only way to modify the carrying capacity multiplier is by overriding `flags.dnd5e.powerfulBuild` to `true`, since [the capacity is based only on strength, that flag, and character size](https://github.com/foundryvtt/dnd5e/blob/3edc7796236bf89cc91963da8ccc306e66e6f01a/module/documents/actor/actor.mjs#L493-L510). This works in some cases as a workaround, but not for small creatures like Halflings,  creatures that already have Powerful Build like Loxodons, or gargantuan creatures.

The easiest way I see to fix this would be to have some attribute key defaulting to 0 that effects could modify and gets [added to mod](https://github.com/foundryvtt/dnd5e/blob/3edc7796236bf89cc91963da8ccc306e66e6f01a/module/documents/actor/actor.mjs#L496). Other modifiers could be implemented too, e.g. a constant addition or subtraction to total carrying capacity, but I don't know any official effects that do something like that.

**Comment by Zanderaf** [comment]
Yea, having the carry weight capactiy being increased multiple times would be something useful, for stuff like Bull Strength, Powerful Build, Bear Totem Carry weight, etc

**Comment by arbron** [comment]
This would definitely have to be separate from the existing powerful build flag, because they behave differently. Powerful build treats you as one creature size larger in terms of your carrying capacity multiplier (so small creatures don't get any increase because they have the same multiplier as medium creatures, and gargantuan creatures don't have a larger size) while features like Bull's Strength explicitly double your carrying capacity, regardless of size.
