### ISSUE TITLE
Spells not completing since last system update

### ISSUE THREAD

**Issue by EvldoaTV** [foundryvtt/dnd5e#3315]
getting this error with a number of spells like witch bolt, entangle and fairie fire since latest 5e update'
the roll isnt completing in the chat cards

acttive-effect.mjs:426 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'id')
[Detected 1 package: system:dnd5e]
    at ActiveEffect5e.createConcentrationEffectData (active-effect.mjs:426:31)
    at Actor5e.beginConcentrating (actor.mjs:1112:33)
    at Item5e.use (item.mjs:1028:39)

**Comment by arbron** [comment]
Is this with all modules disabled? I have seen this issue with Midi-QoL users before.

**Comment by krbz999** [comment]
This happens because a module has removed the default concentration effect.

**Comment by EvldoaTV** [comment]
Midi Qol was disabled as well as DAE at the time yes but I will go through and what other mods have that deal with concentration thank you

**Comment by EvldoaTV** [comment]
Dfreds CE was the culprit

**Comment by Ed1013** [comment]
> Dfreds CE was the culprit

That's right I was running into the issue, they also have a workaround while they work on the final fix:

_In the Module Settings, switch Modify Status Effects to None or Add.
You can still apply the effect with the Convenient Effects toolbar

The issue only happens because Replace does not take into account the new (3.x.x?) dnd system changes related to Concentration warnings before casting spells._

From https://github.com/DFreds/dfreds-convenient-effects/issues/321#issuecomment-2021175174
