### ISSUE TITLE
Spell materials aren't consumed

### ISSUE THREAD

**Issue by Galacic-Glitch** [foundryvtt/dnd5e#3490]
When casting a spell that consumes a material the material isn't consumed. I tested a PC who had revivify with 5 supplies and after 10 castings the supply never went bellow 5.

**Comment by Fyorl** [comment]
Is this when using the 'spellcasting materials', or when setting up consumption via the 'resource consumption' field on Item sheets?

**Comment by Galacic-Glitch** [comment]
Using the 'spellcasting materials'. Added a pic just in case I missed something and to double make sure we talking about the same thing.
![example](https://github.com/foundryvtt/dnd5e/assets/164553958/c13e629c-5157-4d60-b51f-57cd30981535)

**Comment by Fyorl** [comment]
The additional fields you have in your screenshot are provided by a module. Please ensure you have all modules disabled before raising bug reports on the core system tracker.

**Comment by krbz999** [comment]
They are not from a module. They just don't do anything. There is no functionality in the system to consume spell components, these fields just serve as reminders.

**Comment by Fyorl** [comment]
You are right, my mistake.

**Comment by AndrewBurian** [comment]
>There is no functionality in the system to consume spell components

Not true! Just not setup by default. The system does actually have a relatively rich ability consumption system that works for ammo, hit die, and _materials_.

For each spell you want to consume material components, down in the "Spell Casting" section, there's a field for "Resource Consumption" and if you set that to "material" it offers the option to consume one or more items that have to be in the actor's items.

When you configure this setting from an actor's sheet, the only materials you can set as targets are the ones that actor already has on them, but if you configure this setting on a spell from the items page or compendium, you can set a compendium UUID as the target. The issue is that the SRD doesn't explicitly list all of the consumed spell components anywhere and so unlike ammunition, there is nothing to link to by default.

I would personally love to see consumption of spell components with a cost linked automatically. I think the reason most parties don't track them is it's tedious and error prone, but that tedium is mostly solved with a VTT that supports it.

Seems like the change for loading weapons would be simple enough, since the ammunition is already in the compendium it would just require the details to be added to the weapons. Spell components are harder since we'd have to probably create a new compendium for material components including art and whatnot, then also link them. I think they would still clearly count as SRD material even if they're only ever mentioned in spell descriptions. It might also be a breaking change to the default behavior of weapons so there would likely need to be either a world setting or per-item setting added to use them that starts defaulted to false.

Would this be a feature worth considering?

**Comment by kaelad02** [comment]
I think we should reopen this issue with the changes activities bring. You could have an activity consume the material costs when the activity is used.

**Comment by krbz999** [comment]
> I think we should reopen this issue with the changes activities bring. You could have an activity consume the material costs when the activity is used.

I'd be curious what a proposed solution would be.

The existing implementation for consumption works well enough if the spell component is something like "1 leaf" but how about "a diamond worth 300 gp"? Should regular diamonds work? They aren't worth 300 gp. What about diamond dust?

**Comment by Zanderaf** [comment]
It'd be a great thing to add but yea- having the material component be able to be a lot of things makes it weird. "Diamonds worth at least 300 gold" could be several diamonds or a single one.

**Comment by kaelad02** [comment]
I'd use it for the Find Familiar spell. I can buy the incense and put the number of uses in the Supply field. Now that I think about it, the Material consumption could work too, linked to an Incense loot item.

It's not necessary to use Supply since a separate Material item consumption could work. It just seems really odd because how fancy the activity consumption is, but it skips over the spell's material component supply/cost. If there was only the text field and the "consumed" checkbox, that would be fine... and clear that it was just descriptive. But having supply/cost there w/ the "consumed" checkbox implies to me that they'd be consumption targets for the activities.
