### ISSUE TITLE
Proficiency types revert to untranslated as of 3.1.2

### ISSUE THREAD

**Issue by BrotherSharper** [foundryvtt/dnd5e#3587]
Basically these parts here.
![image](https://github.com/foundryvtt/dnd5e/assets/41280723/46ad7397-0885-4c92-8f55-37128e95c026)

How it used to work on 3.1.0 prior is that DnD5e defined objects such as "DND5E.weaponIds" and labeled the key and ID for each proficiency type. i.e. 
"battleaxe": "I0WocDSuNpGJayPb"
And when these items were translated via babele, the sheet would pick up the correct translated name and show that instead.

As of 3.1.2 proficiencies do not seem to be picked up by the sheet anymore even though they are translated by babele and should be pointing at the correct location.

I believe this could be some load order issue. I'd really appreciate if you could look into this and if there's anything on the localization side that can be done to fix this.
(I have thought up of having an invisible compendium of pre-localized items and exchanging the ids on loadup, but it seems convoluted)

**Comment by arbron** [comment]
Hmm, I'm not sure this is a load order issue because those values are only pulled when you first open the configuration app, so Babel should have plenty of time to translate them. I'm thinking it might be an issue with compendium indexes not being translated because we are only loading the index, not the full items.

Might be worth bringing up with the Babel developers to see if that is the case, since I'm not familiar enough with how that module works to say.

**Comment by phenomen** [comment]
Works fine for me on 3.2.0. It pulls names from the Compendium during the loading. Make sure you initialize Babele on `init` hook.

![image](https://github.com/foundryvtt/dnd5e/assets/138311/e7356561-a0a2-47d6-ae9e-2e684388b932)

**Comment by BrotherSharper** [comment]
@phenomen 
Thanks for confirming, this seems to have been a 3.1.2 bug which was fixed when updating to 3.2.0
