### ISSUE TITLE
Non-existent translation keys in the Advancement flow

### ISSUE THREAD

**Issue by phenomen** [foundryvtt/dnd5e#3611]
The following strings are displayed as keys instead of proper values:
```
DND5E.TraitSkillsPlural.few
DND5E.AdvancementAbilityScoreImprovementPointsRemaining.few
DND5E.AdvancementAbilityScoreImprovementPointsRemaining.many
DND5E.AdvancementAbilityScoreImprovementCapDisplay.few
```
**They do not exist in the `en.json`** and also they're not bugged when I use English localization.

![image](https://github.com/foundryvtt/dnd5e/assets/138311/354e0c57-5ca9-4429-901b-1ed411502ebe)

![image](https://github.com/foundryvtt/dnd5e/assets/138311/2f376d0e-8fe4-40a5-891c-8f4d3af8b75a)

**Comment by Fyorl** [comment]
We are using [`Intl.PluralRules`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules) to provide better localisation for these cases. In English these will only ever resolve to `.one` or `.other`, which do have corresponding keys in `en.json`, which is why they work. Other languages can return different values from `PluralRules#select`, such as the `few` or `many` in your screenshot.

You should check which plural rules your language supports. There will not be a 1:1 mapping to English localisation keys for this reason, but generally wherever you find `.one` or `.other` you can assume that you may need additional keys for other languages.

**Comment by phenomen** [comment]
Thanks, I added custom keys to the localization.
