### ISSUE TITLE
Add CONFIG option to prevent grouping damage parts by type

### ISSUE THREAD

**Issue by nschoenwald** [foundryvtt/dnd5e#3652]
All that's needed here is a simple conditional check that skips the `aggregateDamageRolls()` function call in `_enrichDamageTooltip()` and uses the full roll array that's given in the parameters instead of creating its own with aggregated rolls. It's a relatively trivial change comparatively, the only work would be making sure it is correctly passed in via options.

![image](https://github.com/foundryvtt/dnd5e/assets/110994627/bf7f63a9-38e7-466f-bcfd-d8798bddac01)

_Originally posted by @MangoFVTT in https://github.com/foundryvtt/dnd5e/issues/3199#issuecomment-2020702042_

**Comment by leborat** [comment]
Looks like this is the same request, minus the coding specs from the thread i created. I see you commented there as well and are quoting mango: https://github.com/foundryvtt/dnd5e/issues/3199

It was marked as "wont change". Hopefully this gets implemented so at least modders are able to utilize that function. 

Thanks for following up on the topic!

**Comment by ralph2190** [comment]
I installed 3.3.0 and can't seem to find this config option anywhere. Anyone know where it is?

**Comment by unsoluble** [comment]
Via the `CONFIG.DND5E` object, programmatically. To follow up, and for all general questions about using the system, head over to the #dnd5e channel on the Foundry discord.

**Comment by MangoFVTT** [comment]
So adding this CONFIG is a good step to closing this ticket, but it doesn't actually do anything as implemented in #3769, because the tooltip itself doesn't care about the aggregated/non-aggregated damage roll array and simply does its own aggregation by damage type.

I've made a PR to actually use this CONFIG options intended, which will _actually_ fix this issue: #3885
