### ISSUE TITLE
[v3.3.0] NPC sheet and token portrait images being cut

### ISSUE THREAD

**Issue by thatlonelybugbear** [foundryvtt/dnd5e#3847]
That is the SRD Young Green dragon. Some tweaking of the elements to actually not cut the token art would be great!

![image](https://github.com/user-attachments/assets/6e763748-1bab-47a4-a59d-b04a0de50836)

**Comment by Fyorl** [comment]
This design is deliberate, it's just unfortunately not suited for this particular style of token art.

**Comment by thatlonelybugbear** [comment]
Does that mean that the SRD monsters will be updated to use better suiting Art ?

**Comment by Fyorl** [comment]
No, the SRD monster art works very well on the canvas. The new NPC sheet does not accommodate this art ideally, but it's hardly unusable.

**Comment by Rabulias** [comment]
I usually put a portrait instead of the token art in that place, so this does not bother me, but just as an idea, would it be very difficult to add some image display controls to that field like there is on a token? This would allow users to flip, rotate and/or resize the token art in the portrait field.
