### ISSUE TITLE
Cannot edit portrait art if previous file path is unavailable

### ISSUE THREAD

**Issue by Nikkie1110** [foundryvtt/dnd5e#3863]
When a token has artwork or a token image that cannot be found, the AC / Health bar will move up and overlap the image area, preventing the ability to change the art location.   Perhaps a buffer area above the AC / HP bar can be added to give a bit of space and allow for changing art / settings.
![image](https://github.com/user-attachments/assets/af6c8610-2d80-4589-a122-20ce8d17413f)

**Comment by Rabulias** [comment]
I guess it should default to the "mystery man" again?

**Comment by kaelad02** [comment]
It's strange. The CSS looks fine but clearly doesn't work. There's an explicit `height` and `width` that's not really working. Should be 180x180 and it's more like 49x16.

Using the dev tools, I put a `min-height` and `min-width` there and it fixes the issue. I'm not 100% sure that's the right fix or not, meaning it works but is it really covering something up rather than fixing an underlying issue.
