### ISSUE TITLE
New "Activities" need a way to have saving throws on attack activities

### ISSUE THREAD

**Issue by MythicPalette** [foundryvtt/dnd5e#4219]
As the title says, there is seemingly no way for an action to be an attack that also has a saving throw. It seems it has to be created as two activities. It would be nice to have a way to do this. For example, Ray of Sickness. It is an attack spell that you make a ranged spell attack for. If the spell hits, the target must make a constitution saving throw. Right now, this has to be created as two different activities.

**Comment by LadyDefile** [comment]
Something my friend suggested in the same vein as this is chaining activities. For instance say you do an attack activity.
You roll attack.
You miss.
Nothing happens.

You roll attack.
You hit.
Roll Damage.
Rolling damage triggers chained activity "Save"

Obviously, it'd be configurable so that you can set what chains into what. Maybe identifiers, maybe just a list of activities on the current item.

**Comment by M0nk3yy** [comment]
Might be covered by "Forward" Activities in the future per #4031.

**Comment by LadyDefile** [comment]
Sounds like a similar concept. Just some way of triggering secondary activities would be good.

**Comment by Fyorl** [comment]
> Right now, this has to be created as two different activities.

Yes, that is how activities are intended to be used.

**Comment by arbron** [comment]
This is related to the idea of "Follow-Up" activities discussed in the original activities proposal: https://github.com/foundryvtt/dnd5e/issues/1964

Not something we had time for in this version, but something that will be coming later.
