### ISSUE TITLE
The 'Orb' SRD item is a weapon

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#4337]
_That's hard to ponder._

Should just be a trinket, equipment, or loot-type item, and shouldnt have any activities.

Also the case for
- Yew Wand
- Wand
- Sprig of Mistletoe
- Rod

**Comment by M0nk3yy** [comment]
They're a bit weird since a Focus is arguably the "weapon" of a caster. Equipment is more predominantly "wearable" items rather than "holdable" items, and Loot isn't equippable at all. At least that is what I imagine the original thought process to have been considering. Lines also blur as other common focus types - staffs - can be used as a weapon. So the expectation would probably be that you see them in the same place.

Could leave them as weapons but remove attacks?

If not, Trinket Equipment probably preferable to Loot.

**Comment by krbz999** [comment]
Trinket (equipment) would be preferrable to a weapon.
