### ISSUE TITLE
items Sheets not displaying updated properties after being enchanted

### ISSUE THREAD

**Issue by davidR1974** [foundryvtt/dnd5e#4364]
dnd version : 4.0.2
foundry version : 12.331
0 modules enabled

items Sheets display the properties of the initail item and not the overriden properties given by the enchantment.
Enchantment has : 

![image](https://github.com/user-attachments/assets/6e3f201b-f75a-4f76-ad4a-2475675e687b)

system.properties and overrides  are correctly set up after enchantement is applied but do not reflect in the weapons properties of the item sheet

![image](https://github.com/user-attachments/assets/750020d0-148d-42d0-addc-127ed5f1cfff)

note that this work from tsystem perspective :
=> the "Attunement" section appears, meaning that the item is considered magical (and the magical icon shows on the inventory tab of the PC)
=> the Ammunition section is not shown when launching an attack with the enchanted weapon and the "Use Ammunition' section disapparead from the item sheet.

**Comment by arbron** [comment]
That is intentional at the moment, so the underlying data can still be edited properly. In a future version there is a plan to make more use of the edit toggle on item sheets so in editing mode it will show the underlying values before enchantment, and then in play move it will show the values post-enchantment (but they will be locked).

**Comment by krbz999** [comment]
re: #4833
