### ISSUE TITLE
Add post-configuration hooks for rolls

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#4383]
While doing some work on a module, I wanted to determine something from, say, the attack mode of an Attack roll. The pre hook gives access to all the modes that are available, not the one chosen (because one has not been chosen yet), and the post hook is after the roll is fully evaluated and the chat message created, which is too late.

It would be good to have a hook for when the roll configuration dialog is closed and the roll fully configured, using the same parameters if possible.

**Comment by arbron** [comment]
Would a hook that is called after the roll is constructed, but before it is evaluated be sufficient? Or would you need a hook after the configuration is complete but before the roll configuration objects are converted into actual roll instances be needed?

**Comment by krbz999** [comment]
I think either would work, but prior to the construction of the roll instances would be ideal as it would allow me to work with the same (or similar) constructs as in the current hooks.

The important part is whether or not the rolls can be changed (adding additional parts, modifiers, etc.).

**Comment by arbron** [comment]
I'll start by adding one after the rolls have been constructed, because that is the only place where cancelling the rolling process makes sense and Honeybadger has need of that part specifically. Once that is in we can see about potentially adding more, but the pre-construction is a bit more difficult because it would need to be called every time the roll configuration dialog is changed.
