### ISSUE TITLE
Enchanted ammunition damage is not applied if used through a weapon

### ISSUE THREAD

**Issue by InnilToo** [foundryvtt/dnd5e#4405]
When I enchant arrow and the attack and damage with a short bow that used those arrows, the extra damage enchantment is not reflected.

Steps to reproduce:
1. Make a New Item.
2. Give it an Enchant activity.
3. Give it and effect like `system.damage.parts | Add | [["1d3", "fire"]]`.
4. Use the new to enchant an ammunition like arrows.
5. Attack with the a weapon that consumes the enchanted ammunition like bow.
6. Damage with the weapon.
7. Ponder why the extra damage is missing.

**Comment by krbz999** [comment]
Related: #2123

**Comment by arbron** [comment]
There is a related bug, but you will have to use the base damage for this when applying to ammunition because only the base damage gets applied to weapon attacks:
<img width="584" alt="Screenshot 2024-11-05 at 12 59 09" src="https://github.com/user-attachments/assets/dc8c23fb-d533-4f1c-be8e-b91ab76cae48">

**Comment by arbron** [comment]
There is also a related bug that prevents enchantments that modify a weapon's versatile damage from applying correctly.
