### ISSUE TITLE
Damage Rolls not Respecting Roll Privacy (Visual Bug)  

### ISSUE THREAD

**Issue by MisterQue77** [foundryvtt/dnd5e#4533]
### What happened?

![Bug](https://github.com/user-attachments/assets/40816b99-ab38-49c6-882e-bfb50405383e)
I noticed during my set up that it appeared to be setting my damage rolls to Public, despite the overall setup being Private GM. I tested without any modules and it was still an error, but upon looking on player end, it appears to be correct on the players side. I assume its a visual error of some kind.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

5e

### What core version are you reporting this for?

Latest

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
The default roll mode applies to automated or chat-based rolls which do not otherwise specify an explicit roll mode. For a damage card like this, the explicit roll mode of the damage roll takes precedence. This is a dnd5e system design choice so this issue could be raised there, although I'm certain it is an intentional choice.
