### ISSUE TITLE
Support for NPC sheet to display Death Saves.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#456]
Originally in GitLab by @apoapostolov

Support for NPC sheet to display Death Saves. This is mentioned in DMG, and many DM feel like named NPCs should be allowed the same recovery chance as PCs especially when friendly allies in combat.

**Comment by BlackBadger777** [comment]
I'll join the minority in requesting this. Would be really useful for the kinds of campaigns I run, but I acknowledge that this might be an edge case that isn't that useful for the wider 5e community. Still, I thought my 2 cents might be worth something.

**Comment by kgar** [comment]
## We Should Totally Support This

Hello from the future! 🙋‍♂️

Almost any campaign I run has the chance of an NPC needing to roll death saves. I just ended a session where a beloved NPC was rolling death saves while being carried away from danger. This is not an edge case for me. I think it would be a great addition to the NPC actor type and sheet.

If it were opt-in via dnd5e config settings, that may smooth things over a bit, but honestly, it could just be put out there, and I would use it when needed and otherwise ignore it.

I noticed that the base actor class has the `rollDeathSave` function, but the NPC subclass lacks the appropriate system data to support it :/

If one were to attempt to call this base class function from an NPC actor, here is the result:

![image](https://github.com/foundryvtt/dnd5e/assets/4632129/48184f36-cadc-41ad-b096-3551f80e5a8d)

![image](https://github.com/foundryvtt/dnd5e/assets/4632129/881d81e4-7bcc-4e67-b8e2-60bbb9e28d0b)

## Modules Cannot Cleanly Manage NPC Death Saves

Regarding leaving it to modules to do this, they cannot do it fully, not without copy/pasting unexported classes from dnd5e. Namely, if an NPC is set up with Diamond Soul (it's a thing that can be done), then the `Proficiency` class is used in order to create a `term` which is fed into the death save:

```js
    // Diamond Soul adds proficiency
    if ( this.getFlag("dnd5e", "diamondSoul") ) {
      parts.push("@prof");
      data.prof = new Proficiency(this.system.attributes.prof, 1).term;
    }
```

Modules don't have access to the `Proficiency` class, so they cannot do it unless they copy/paste the dnd5e system classes and try to make sure they stay synchronized. Not fun.

**Comment by krbz999** [comment]
> Modules don't have access to the `Proficiency` class, so they cannot do it unless they copy/paste the dnd5e system classes and try to make sure they stay synchronized. Not fun.

`dnd5e.documents.Proficiency`

**Comment by kgar** [comment]
@krbz999 that is beautiful, and you have helped with an unrelated matter. Thank you!
I tried finding it via code and forgot to look there 🤦‍♂️

However, redoing death save logic in a module is not a great prospect, even with that class available.

**Comment by kgar** [comment]
> > Modules don't have access to the `Proficiency` class, so they cannot do it unless they copy/paste the dnd5e system classes and try to make sure they stay synchronized. Not fun.
> 
> `dnd5e.documents.Proficiency`

Is there a way to cleanly add the `death` schema to an NPC in a module? Or is that something that is better done to the system class?

I started working on a PR for this, and I found that all I needed to do for the NPC actor was add the death schema:

![image](https://github.com/foundryvtt/dnd5e/assets/4632129/9bb08561-9776-4793-9903-2301be40bad6)

The base actor logic handles everything else with death save rolls.

The sheets are another matter, but also not too bad.

**Comment by MaxPat931** [comment]
> If it were opt-in via dnd5e config settings, that may smooth things over a bit, but honestly, it could just be put out there, and I would use it when needed and otherwise ignore it.

Maybe if it were a toggle in the Special Traits section? So that way it's still opt in, but I think this would make more sense than all NPCs or nothing?

**Comment by kgar** [comment]
From my own experience, I would generally always want the option available for all my NPCs, should the need arise. That is, I wouldn't want to have to toggle it for each NPC individually. I only suggest the config setting to account for those who don't want it and wouldn't want to see it on the sheet at all, since it does take up real estate.

**Comment by krbz999** [comment]
There's a reference up above here to official material that seems to go overlooked.

> Mighty villains and special nonplayer characters are common exceptions; the DM might have them fall unconscious and follow the same rules as player characters.

Which seems to beg the question of why 'mighty villains' and 'special nonplayer characters' would not be a `character` rather than an `npc`.

If they are 'special' or 'beloved', it seems to imply they would be able to survive an encounter. By surviving an encounter, they would benefit from the ability to take a short or long rest (also not available on `npc` sheets). This snowballs into adding more and more `character` features to `npc`s, at which point said actor should have been made as one long ago.

**Comment by Mythano** [comment]
Agree with everything krbz999 said.  It's more common to have many  npcs that just *die* , then it is to have death saving throws for *every* NPC.   To have it on by default, or on every NPC sheet is overkill, when the simple solution is just to make these special / beloved NPCs as character sheets, not NPC sheets.

**Comment by thatlonelybugbear** [comment]
Might I offer a different view though?

As this is a reference from official material, why should the system not cater for this? 

A special trait checkbox to turn it on the specific NPC, nothing by default on or viewable, would have almost 0 impact to whomever doesn't want to use it, but would help immenselly whoever wants to 🤷 

Not a directly linked example could be the critical damage options offered by the system.

**Comment by BlackBadger777** [comment]
> Might I offer a different view though?
> 
> As this is a reference from official material, why should the system not cater for this?
> 
> A special trait checkbox to turn it on the specific NPC, nothing by default on or viewable, would have almost 0 impact to whomever doesn't want to use it, but would help immenselly whoever wants to 🤷
> 
> Not a directly linked example could be the critical damage options offered by the system.

I agree with thatlonelybugbear. Since NPCs *can* have death saves per RAW, the *NPC* sheet should habour options that reflect this, no?

**Comment by Mythano** [comment]
I rarely comment here, but only added my opinion after the suggestions were made that it should be on by default to prevent *having to change all my npcs individually* , which is backwards to **most** NPCs dont require death saves.  Could it be included? Sure.   Does it need to be on default? Absolutely not.

**Comment by BlackBadger777** [comment]
Agreed, it definitely doesn't need to be on by default. Just a toggle would be awesome though.

**Comment by aaclayton** [comment]
Part of the challenge is that you might not know ahead of time which NPC meets the criteria for being a significant and impactful character. Someone you may have initially set up as an NPC might get into a situation where you deem that death saves are important. 

I think it would be worth investing in a two-way type conversion that would support `character` <-> `npc`. This could allow you to "upgrade" a NPC to be a "Character" if circumstances necessitate that while still keeping character-specific functionalities like death saves, rest mechanics, etc... reserved for that data model while keeping NPC-specific behaviors like legendary actions, lair actions, etc... reserved for that data model.

**Comment by kgar** [comment]
If NPC death saves do not get visualized at all, is there a possible compromise where `NPCData` can have `death` schema so that module developers can support NPC death saves without copy/pasting the death save roll code from the base actor class?

**Comment by voodoofrog** [comment]
Personally, I don't think NPCs should be run with a character sheet. I like the idea of a toggle being available for standard NPCs.
