### ISSUE TITLE
Deleting a spellcasting class from an actor doesn't fully clear the information about spell slots

### ISSUE THREAD

**Issue by Sillsoft42** [foundryvtt/dnd5e#4602]
Foundry version: 12.331
dnd5e version: 4.0.4

1. create a fresh new actor and give it the cleric class, doing the full level 1 advancement and toggle the spell slots as being unused
2. delete the class and add the warlock class, doing the full level 1 advancement
3. add a 1st level spell and then notice that when you cast it, you still get an option to cast it using the normal 1st level spell slots in addition to the normal pact magic slot

**Comment by arbron** [comment]
We don't automatically limit the number of spell slots because there are abilities that let you create ephemeral spell slots above the maximum allowed of a certain level. The way to resolve this is to just always take a Long Rest after you have modified the class on your character to ensure everything is properly reset.
